services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: notes2gogo_db
    environment:
      POSTGRES_DB: notes2gogo
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notes_user -d notes2gogo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notes2gogo_network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes2gogo_backend
    environment:
      - DATABASE_URL=postgresql://notes_user:notes_password@database:5432/notes2gogo
      - SECRET_KEY=super-secret-key-change-in-production
      - DEBUG=true
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - notes2gogo_network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notes2gogo_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - notes2gogo_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  notes2gogo_network:
    driver: bridge